"""
scaffold_report.py - create analysis/<report>/ with ready-to-fill plan, analysis, checks and
report scripts, so agents write only the parts specific to the question.

Used by the Quick Report agent (fast path) and optionally by the Analyst (full flow).
The generated scripts already handle loading, logging, output files, the standard validation
checks and an automatic report layout; each has a small "FILL IN" block. It also writes the
report manifest (report.json) that registers the report's inputs and domain packs.

Treasury-aware defaults (from the profile's confirmed annotations):
  - additive measure (flows: payments, interest)      -> headline = sum over the rows in scope
  - semi-additive measure (stocks: balances, positions, outstanding) -> headline taken at ONE
    as-of date (latest date in scope by default), never summed across dates
  - non-additive measure (rates, ratios)               -> refused as the headline measure;
    use the amount it applies to and compute a weighted average in the FILL IN block
  - a currency column in the main input                -> a check that the headline is in a single
    currency, or that a conversion step was added (set CONVERTED = True once it is)

Search first so you don't build a duplicate:  python tools/reports.py find "<question words>"

Usage (names are illustrative):
  python tools/scaffold_report.py cash_position_daily \
      --source bank_balances:Balances --measure "Closing Balance" \
      --title "Daily cash position" --question "What is the cash position by entity and bank?" --quick

  --source       source_id:sheet (preferred - always reads the current file of a recurring source)
                 or profile_name:sheet for a one-off file. A profile that belongs to a registered
                 source is converted to that source automatically.
                 Repeat for each input; the first is the main table.
  --measure      column of the main measure in the first input
  --as-of-column date column that says WHEN the position is (reporting / snapshot / balance date).
                 Default: a date column with a single value (a snapshot), else one named like
                 "reporting/as of/snapshot/position/balance date", else the first date column.
  --bucket-column date column to bucket the position BY (maturity, due, repricing date), measured
                 from the as-of date. Adds cumulative "next N days" windows and a by-year table to
                 analysis.py, and matching independent checks to checks.py. Never the as-of column.
  --currency     label prefix for amounts in the report, e.g. "EUR " (default: none)
  --question, --owner, --schedule, --tag   recorded in report.json
  --quick        mark as a fast-path report (review level "quick")
  --force        overwrite existing files
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from tools.knowledge import load_sources, match_source  # noqa: E402
from tools.load_data import load_profile, source_profile_name  # noqa: E402
from tools.domains import recorded_domains  # noqa: E402
from tools import reports  # noqa: E402

CURRENCY_COL = re.compile(r"(?i)\b(currency|ccy|cur)\b")
AS_OF_NAME = re.compile(r"(?i)report|as.?of|snapshot|position|balance|closing|eod")
BUCKET_NAME = re.compile(r"(?i)matur|due|expir|repric|settle|payment")
WINDOWS = [7, 30, 90, 365]

PLAN = '''# Analysis plan: __TITLE__

**Type:** __TYPE__
**Requested by:** FILL IN
**Date:** __DATE__
**Question:** __QUESTION__
**Domain packs:** __DOMAINS__

## Data (from confirmed profiles)
| Source | Sheet | Grain |
|---|---|---|
__SOURCES__

## Measures (cite knowledge/glossary.md; if missing, a domain pack starter definition marked NEW)
- __MEASURE__: __ADDITIVITY__ - FILL IN definition and citation
- FILL IN other measures

## Filters, as-of date / time window, currency, joins
- FILL IN (e.g. as-of date, statuses in scope, reporting currency and FX rate date, joins)

## Outputs (output/)
- kpis.json - headline numbers
- FILL IN one CSV per table, e.g. by_entity.csv

## Decisions, lessons and domain traps applied (cite knowledge/)
- FILL IN or "none"
'''

ANALYSIS = '''"""Analysis: __TITLE__. Plan: plan.md. Writes output/. Generated by scaffold_report.py."""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))
from tools.load_data import load_sheet, load_source  # noqa: E402,F401

import pandas as pd  # noqa: E402,F401

OUT = HERE / "output"
OUT.mkdir(exist_ok=True)
logs = {}

# ---- load (logical sources always read the current file; do not change)
__LOADS__

# ============================ FILL IN: analysis ============================
# Keep ratios as 0-1 floats, amounts as plain numbers, business column names.
# kpis must include "rows_in_scope" and the headline measure under KPI_KEY.
# Never add amounts in different currencies without converting them first.
KPI_KEY = "__KPI_KEY__"
in_scope = __MAIN__            # apply the plan's filters (status, entity, currency...) here
__MEASURE_BLOCK__
__BUCKET_BLOCK__
tables = {
__BUCKET_TABLES__    # e.g. "by_entity": __BASIS__.groupby("Entity")["__MEASURE__"].sum().rename("__OUT_MEASURE__")
    #                   .sort_values(ascending=False).reset_index(),
}
# ========================================================================

for old in OUT.glob("*.csv"):  # a table removed from the code must not linger in checks and the report
    old.unlink()
for name, df in tables.items():
    df.to_csv(OUT / f"{name}.csv", index=False)
(OUT / "kpis.json").write_text(json.dumps(kpis, indent=2, default=str))
(OUT / "data_log.json").write_text(json.dumps(logs, indent=2))
print(json.dumps(kpis, indent=2, default=str))
for name, df in tables.items():
    print(f"\\n{name}\\n{df.head(15).to_string()}")
'''

MEASURE_ADDITIVE = '''kpis = {
    KPI_KEY: float(in_scope["__MEASURE__"].sum()),     # additive measure: sum over the rows in scope
    "rows_in_scope": int(len(in_scope)),
}'''

MEASURE_STOCK = '''# "__MEASURE__" is a stock (semi-additive over time): report it at ONE as-of date, never summed over dates.
AS_OF_COL = "__AS_OF_COL__"
as_of = in_scope[AS_OF_COL].max()          # or the as-of date stated in the plan
position = in_scope[in_scope[AS_OF_COL] == as_of]
kpis = {
    KPI_KEY: float(position["__MEASURE__"].sum()),
    "as_of": as_of.strftime("%Y-%m-%d"),
    "rows_in_scope": int(len(position)),
}'''

BUCKET = '''
# ---- bucket by "__BUCKET_COL__", measured from the as-of date (not from today)__AS_OF_FOR_FLOW__
BUCKET_COL = "__BUCKET_COL__"
days_to = (__BASIS__[BUCKET_COL] - as_of).dt.days
WINDOWS = __WINDOWS__                  # cumulative: each window includes the shorter ones (decisions.md)
windows = pd.DataFrame([{
    "Window": f"Next {w} days",
    "__OUT_MEASURE__": float(__BASIS__.loc[(days_to > 0) & (days_to <= w), "__MEASURE__"].sum()),
    "Rows": int(((days_to > 0) & (days_to <= w)).sum()),
} for w in WINDOWS])
windows["Share"] = windows["__OUT_MEASURE__"] / kpis[KPI_KEY]
by_year = (__BASIS__.groupby(__BASIS__[BUCKET_COL].dt.year.rename("__BUCKET_YEAR__"))["__MEASURE__"]
           .agg(["sum", "count"]).set_axis(["__OUT_MEASURE__", "Rows"], axis=1).reset_index())
by_year["Share"] = by_year["__OUT_MEASURE__"] / kpis[KPI_KEY]
for w in WINDOWS:
    kpis[f"next_{w}d"] = float(windows.loc[windows["Window"] == f"Next {w} days", "__OUT_MEASURE__"].iloc[0])'''

AS_OF_FOR_FLOW = '''
AS_OF_COL = "__AS_OF_COL__"
as_of = in_scope[AS_OF_COL].max()
kpis["as_of"] = as_of.strftime("%Y-%m-%d")'''

BUCKET_TABLES = '''    "maturity_windows": windows,           # cumulative - excluded from "sums to headline" checks
    "by_year": by_year,                     # a partition - must sum to the headline
'''

CHECKS = '''"""Checks for __REPORT__. Generated by scaffold_report.py.
Recomputes the headline independently and runs the standard checks automatically."""
import json
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))
from tools.load_data import load_profile, load_sheet, load_source, load_source_profile  # noqa: E402,F401
from tools.validate import Validator  # noqa: E402

REPORT = "__REPORT__"
MAIN = ("__MAIN_NAME__", "__MAIN_SHEET__")
load_main = __MAIN_LOADER__
main_profile = __MAIN_PROFILE_LOADER__
SOURCE_MEASURE = "__MEASURE__"          # column in the source
ADDITIVITY = "__ADDITIVITY__"
AS_OF_COL = __AS_OF_COL_PY__            # when the position is (snapshot / reporting date)
BUCKET_COL = __BUCKET_COL_PY__          # what the position is bucketed by (e.g. maturity date)
WINDOWS = __WINDOWS__
CUMULATIVE_TABLES = __CUMULATIVE__      # overlapping tables: not expected to sum to the headline
CURRENCY_COL = __CURRENCY_COL_PY__
CONVERTED = False                       # set True once analysis.py converts to one reporting currency
KPI_KEY = "__KPI_KEY__"                 # key in output/kpis.json
OUTPUT_MEASURE = "__OUT_MEASURE__"      # column name used in output CSVs
GRAIN_KEYS = __GRAIN_KEYS__             # columns that should be unique together
KEY_COLUMNS = __KEY_COLUMNS__           # dimensions/measures that must not be null

v = Validator(REPORT, review_level="__LEVEL__")
out = HERE / "output"
kpis = json.loads((out / "kpis.json").read_text())

# ---- independent recompute (FILL IN: apply the SAME filters as the plan, written independently)
src, _ = load_main(*MAIN)
in_scope = src

# ---- standard checks (no changes needed)
if ADDITIVITY.startswith("semi_additive") and AS_OF_COL:
    as_of = pd.Timestamp(kpis["as_of"])
    basis = in_scope[in_scope[AS_OF_COL] == as_of]
    v.check("Stock measure taken at a single as-of date", "as_of" in kpis, f"as_of={as_of.date()}")
    v.reconcile(f"Headline {KPI_KEY} at {as_of.date()} vs independent recompute",
                float(basis[SOURCE_MEASURE].sum()), kpis[KPI_KEY])
    v.row_count("Rows at the as-of date", len(basis), kpis["rows_in_scope"])
else:
    basis = in_scope
    v.reconcile(f"Headline {KPI_KEY} vs independent recompute", float(basis[SOURCE_MEASURE].sum()), kpis[KPI_KEY])
    v.row_count("Rows in scope", len(basis), kpis["rows_in_scope"])
if CURRENCY_COL:
    n_ccy = basis[CURRENCY_COL].nunique()
    v.check("Headline in a single currency, or converted", n_ccy <= 1 or CONVERTED,
            f"{n_ccy} currencies: {sorted(basis[CURRENCY_COL].dropna().astype(str).unique())[:8]}")
for csv in sorted(out.glob("*.csv")):
    if csv.stem in CUMULATIVE_TABLES:
        continue
    t = pd.read_csv(csv)
    if OUTPUT_MEASURE in t.columns:
        if ADDITIVITY.startswith("semi_additive") and AS_OF_COL and t.columns[0] == AS_OF_COL:
            # a stock over time is a trend, not a sum: its last date must equal the headline
            v.reconcile(f"{csv.stem}: last date equals headline", kpis[KPI_KEY], float(t[OUTPUT_MEASURE].iloc[-1]))
        else:
            v.reconcile(f"{csv.stem} sums to headline", kpis[KPI_KEY], float(t[OUTPUT_MEASURE].sum()))
    for share in [c for c in t.columns if c.lower().startswith("share")]:
        v.shares_sum_to_one(t[share])
if BUCKET_COL:
    as_of = pd.Timestamp(kpis["as_of"])
    days_to = (basis[BUCKET_COL] - as_of).dt.days
    for w in WINDOWS:
        v.reconcile(f"Next {w} days vs independent recompute",
                    float(basis.loc[(days_to > 0) & (days_to <= w), SOURCE_MEASURE].sum()), kpis[f"next_{w}d"])
    vals = [kpis[f"next_{w}d"] for w in WINDOWS]
    v.check("Cumulative windows never decrease", vals == sorted(vals), " / ".join(f"{x:,.0f}" for x in vals))
    if (days_to < 0).any():
        v.warn(f"{BUCKET_COL} before {AS_OF_COL}",
               f"{int((days_to < 0).sum())} row(s) already past {BUCKET_COL} at the as-of date - matured deals in scope?")
if GRAIN_KEYS:
    v.unique(in_scope, GRAIN_KEYS, label=f"Grain: {GRAIN_KEYS} unique")
v.no_nulls(basis, [c for c in KEY_COLUMNS if c in basis.columns])
for q in main_profile(MAIN[0])["annotations"].get("open_questions", []):
    v.warn("Open question carried into report", q)

# ---- FILL IN: extra checks (joins, domain-pack checks, lessons that apply)

v.save()
'''

BUILD = '''"""Build reports/__REPORT__.html from output/ + validation.json. Generated by scaffold_report.py.
Layout is automatic: one section per output CSV. Fill in the headline and titles."""
import json
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT))
from tools.report_kit import Report, fmt_compact, fmt_money, fmt_num, fmt_pct  # noqa: E402,F401
from tools.validate import load_validation  # noqa: E402
from tools.load_data import describe_logs  # noqa: E402

REPORT = "__REPORT__"
out = HERE / "output"
k = json.loads((out / "kpis.json").read_text())
log = json.loads((out / "data_log.json").read_text())
val = load_validation(REPORT)
tables = {p.stem: pd.read_csv(p) for p in sorted(out.glob("*.csv"))}
money = lambda v: fmt_compact(v, "__CURRENCY__")  # noqa: E731

# ============================ FILL IN ============================
TITLE = "__TITLE__"
SUBTITLE = "FILL IN: what this report covers, in one sentence"
PERIOD = k.get("as_of", "")          # as-of date for positions, or the period for flows
HEADLINE = "FILL IN: the answer as a sentence, built from k[...] / tables[...] values"
DETAIL = ""
KPIS = [
    {"label": "__OUT_MEASURE__", "value": money(k["__KPI_KEY__"])},
]
SECTION_TITLES = {name: name.replace("_", " ").capitalize() for name in tables}  # override per table
FORMATS = {"__OUT_MEASURE__": fmt_money, "Share": fmt_pct}
NOTES = []  # caveats, e.g. currency conversion basis, the profile's not_feasible list
# =================================================================

r = Report(TITLE, subtitle=SUBTITLE, period=PERIOD, sources=describe_logs(log))
r.headline(HEADLINE, DETAIL)
r.kpis(KPIS)
order = [n for n in SECTION_TITLES if n in tables] + [n for n in tables if n not in SECTION_TITLES]
for name in order:  # sections follow SECTION_TITLES order
    t = tables[name]
    r.section(SECTION_TITLES.get(name, name.replace("_", " ").capitalize()))
    label_col = t.columns[0]
    value_col = "__OUT_MEASURE__" if "__OUT_MEASURE__" in t.columns else t.columns[1]
    is_time = bool(pd.to_datetime(t[label_col].astype(str), errors="coerce", format="mixed").notna().all())
    if is_time and len(t) > 2:
        series = {c: list(t[c]) for c in t.columns[1:] if pd.api.types.is_numeric_dtype(t[c]) and c != "Share"}
        r.line_chart(list(t[label_col].astype(str)), series, value_format=money)
    elif len(t) <= 15:
        r.bar_chart(list(t[label_col].astype(str)), list(t[value_col]), value_format=money,
                    highlight=[str(t[label_col].iloc[0])])
    r.table(t, formats={c: f for c, f in FORMATS.items() if c in t.columns})

warnings = [x["detail"] for x in (val or {}).get("results", []) if x["severity"] == "warning"]
if warnings:
    r.callout(" ".join(warnings), title="Needs a decision", kind="warning")
steps = [s for lg in log.values() for s in lg
         if not s.startswith(("  ", "Loaded", "raw rows", "final rows", "source "))]
r.methodology(
    steps=["Data cleaned with confirmed rules: " + ("; ".join(steps) or "none needed"),
           (f"{val['n_checks'] - val['n_failed']} of {val['n_checks']} automated checks passed" if val
            else "Not yet checked")],
    validated=bool(val and val["passed"]), notes=NOTES,
    review=(val or {}).get("review_level", "full"))
print(f"Report written to {r.save(ROOT / 'reports' / (REPORT + '.html'))}")
'''


def py(v) -> str:
    return json.dumps(v).replace("null", "None")


def pick_as_of(columns: list[dict], roles: dict, exclude: str = "") -> str:
    """A single-value date column is a snapshot date; then a date named like one; then the first date."""
    dates = [c for c in columns if roles.get(c["name"]) == "date" and c["name"] != exclude]
    for pick in (lambda c: c.get("distinct") == 1, lambda c: AS_OF_NAME.search(c["name"]), lambda c: True):
        hit = next((c["name"] for c in dates if pick(c)), None)
        if hit:
            return hit
    return ""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("report")
    ap.add_argument("--source", action="append", required=True, help="source_id:sheet or profile_name:sheet")
    ap.add_argument("--measure", required=True, help="column of the main measure in the first input")
    ap.add_argument("--as-of-column", default="")
    ap.add_argument("--bucket-column", default="")
    ap.add_argument("--title", default="")
    ap.add_argument("--currency", default="")
    ap.add_argument("--question", default="")
    ap.add_argument("--owner", default="")
    ap.add_argument("--schedule", default="ad hoc")
    ap.add_argument("--tag", action="append", default=[])
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args()

    if not re.fullmatch(r"[a-z0-9_]+", a.report):
        sys.exit("Report name must be lower_snake_case")
    folder = ROOT / "analysis" / a.report
    if folder.exists() and any(folder.iterdir()) and not a.force:
        sys.exit(f"{folder} already exists (use --force to overwrite)")

    source_ids = {s["id"] for s in load_sources()["sources"]}
    sources, loads, inputs, domains = [], [], [], []
    main = {}
    for i, spec in enumerate(a.source):
        name, sheet = spec.split(":", 1)
        if name not in source_ids:
            owners = match_source(f"{name}.xlsx") or match_source(f"{name}.csv")
            if owners:
                print(f"Note: {name} belongs to logical source '{owners[0]}' - using the source instead, "
                      "so the report always reads the current file.")
                name = owners[0]
        is_source = name in source_ids
        prof = load_profile(source_profile_name(name) if is_source else name)
        sann = prof["annotations"]["sheets"].get(sheet)
        if sann is None:
            sys.exit(f"Sheet '{sheet}' not in {prof['source']['file']}")
        inputs.append({("source" if is_source else "profile"): name, "sheet": sheet})
        domains += [d for d in recorded_domains(prof) if d not in domains]
        var = re.sub(r"[^a-z0-9]+", "_", sheet.lower()).strip("_") or f"src{i}"
        loader = "load_source" if is_source else "load_sheet"
        loads.append(f'{var}, logs["{var}"] = {loader}("{name}", "{sheet}")')
        label = f"source {name} (now {prof['source']['file']})" if is_source else prof["source"]["file"]
        sources.append(f"| {label} | {sheet} | {sann.get('grain') or 'FILL IN'} |")
        if i == 0:
            main = {"var": var, "name": name, "sheet": sheet, "is_source": is_source, "prof": prof, "ann": sann}

    ann, prof = main["ann"], main["prof"]
    sp = next(s for s in prof["sheets"] if s["name"] == main["sheet"])
    roles = ann.get("column_roles", {})
    col_names = [c["name"] for c in sp["columns"]]
    if a.measure not in col_names and a.measure not in roles:
        sys.exit(f"Measure '{a.measure}' is not a column of {prof['source']['file']}/{main['sheet']}. "
                 f"Columns: {col_names}")
    additivity = (ann.get("column_additivity", {}).get(a.measure) or "additive").strip()
    if additivity.startswith("non_additive"):
        sys.exit(f"'{a.measure}' is non-additive (a rate or ratio) and can't be the headline sum. Use the amount "
                 "it applies to as --measure and compute a weighted average in the FILL IN block.")
    is_stock = additivity.startswith("semi_additive")
    bucket_col = a.bucket_column
    if bucket_col and bucket_col not in col_names:
        sys.exit(f"--bucket-column '{bucket_col}' is not a column. Columns: {col_names}")
    date_col = a.as_of_column or pick_as_of(sp["columns"], roles, exclude=bucket_col)
    if bucket_col and bucket_col == date_col:
        sys.exit(f"'{bucket_col}' can't be both the as-of and the bucket column. Pass --as-of-column.")
    if (is_stock or bucket_col) and not date_col:
        sys.exit(f"No as-of date column is known for '{a.measure}'. Pass --as-of-column.")
    bucket_hint = [c for c in col_names if BUCKET_NAME.search(c) and roles.get(c) == "date" and c != date_col]
    currency_col = next((c for c in col_names if CURRENCY_COL.search(c) and roles.get(c) != "unused"), None)

    nrows = sp["n_rows_clean"]
    identifiers = [c["name"] for c in sp["columns"] if roles.get(c["name"]) == "identifier"]
    grain_keys = [c["name"] for c in sp["columns"] if roles.get(c["name"]) == "identifier"
                  and c["distinct"] >= nrows - sp["duplicate_rows"]]
    if not grain_keys and is_stock and identifiers:
        grain_keys = identifiers[:1] + [date_col]      # e.g. one balance per account per day
    key_cols = [c for c, r in roles.items() if r in ("dimension", "measure", "date") and c in col_names]
    cat = next((c.get("catalog", {}) for c in sp["columns"] if c["name"] == a.measure), {})
    kpi_key = cat.get("id") or re.sub(r"[^a-z0-9]+", "_", a.measure.lower()).strip("_")
    out_measure = (cat.get("label") or a.measure) if cat.get("match") == "confirmed" else a.measure
    title = a.title or a.report.replace("_", " ").capitalize()

    subs = {"__TITLE__": title, "__REPORT__": a.report, "__DATE__": date.today().isoformat(),
            "__TYPE__": "Quick report (fast path)" if a.quick else "Full review",
            "__QUESTION__": a.question or "FILL IN - one sentence",
            "__DOMAINS__": ", ".join(domains) or "none recorded",
            "__SOURCES__": "\n".join(sources), "__LOADS__": "\n".join(loads), "__MAIN__": main["var"],
            "__MEASURE_BLOCK__": MEASURE_STOCK if is_stock else MEASURE_ADDITIVE,
            "__BASIS__": "position" if is_stock else "in_scope",
            "__MAIN_NAME__": main["name"], "__MAIN_SHEET__": main["sheet"],
            "__MAIN_LOADER__": "load_source" if main["is_source"] else "load_sheet",
            "__MAIN_PROFILE_LOADER__": "load_source_profile" if main["is_source"] else "load_profile",
            "__BUCKET_BLOCK__": BUCKET if bucket_col else "",
            "__AS_OF_FOR_FLOW__": AS_OF_FOR_FLOW if bucket_col and not is_stock else "",
            "__BUCKET_TABLES__": BUCKET_TABLES if bucket_col else "",
            "__BUCKET_COL__": bucket_col, "__BUCKET_YEAR__": f"{bucket_col} Year",
            "__BUCKET_COL_PY__": py(bucket_col or None), "__WINDOWS__": json.dumps(WINDOWS),
            "__CUMULATIVE__": json.dumps(["maturity_windows"] if bucket_col else []),
            "__ADDITIVITY__": additivity, "__AS_OF_COL__": date_col,
            "__AS_OF_COL_PY__": py(date_col or None),
            "__CURRENCY_COL_PY__": py(currency_col),
            "__MEASURE__": a.measure, "__KPI_KEY__": kpi_key, "__OUT_MEASURE__": out_measure,
            "__GRAIN_KEYS__": json.dumps(grain_keys), "__KEY_COLUMNS__": json.dumps(key_cols),
            "__LEVEL__": "quick" if a.quick else "full", "__CURRENCY__": a.currency}

    similar = [(s, m) for s, m in reports.find(f"{title} {a.question}") if m["report"] != a.report]
    same_inputs = [m["report"] for m in reports.all_manifests()
                   if m["report"] != a.report and {reports._key(i) for i in m["inputs"]} == {reports._key(i) for i in inputs}]
    if similar or same_inputs:
        print("Existing reports that may already answer this (consider reusing or extending them):")
        for r in dict.fromkeys(same_inputs + [m["report"] for _, m in similar[:3]]):
            m = reports.load_manifest(r)
            print(f"  - {r}: {m['title']} | {m.get('question') or '-'}")

    folder.mkdir(parents=True, exist_ok=True)
    for fname, tpl in (("plan.md", PLAN), ("analysis.py", ANALYSIS), ("checks.py", CHECKS),
                       ("build_report.py", BUILD)):
        text = tpl
        for _ in range(2):  # measure block contains placeholders itself
            for key, val in subs.items():
                text = text.replace(key, val)
        (folder / fname).write_text(text, encoding="utf-8")
    reports.save_manifest(reports.new_manifest(a.report, inputs, title, a.question,
                                               "quick" if a.quick else "full", a.owner, a.schedule, a.tag,
                                               domains=domains))
    print(f"Scaffolded {folder.relative_to(ROOT)}: plan.md, analysis.py, checks.py, build_report.py, report.json")
    print(f"Main measure '{a.measure}' ({additivity}) -> kpis['{kpi_key}'], output column '{out_measure}'")
    if is_stock:
        print(f"Stock measure: headline taken at one as-of date using '{date_col}'.")
    if bucket_col:
        print(f"Bucketed by '{bucket_col}' from the as-of date: cumulative windows {WINDOWS} days + by year.")
    elif bucket_hint:
        print(f"Tip: to bucket by {bucket_hint[0]!r} (maturity ladder / by year), re-run with "
              f"--bucket-column \"{bucket_hint[0]}\" --force.")
    if currency_col:
        print(f"Currency column '{currency_col}': convert to one currency or filter, then set CONVERTED in checks.py.")
    print(f"Grain keys: {grain_keys or 'none detected - set GRAIN_KEYS in checks.py'}")
    print(f"Domain packs: {', '.join(domains) or 'none recorded'}")
    print("Next: fill the FILL IN blocks, then python tools/run_pipeline.py " + a.report)


if __name__ == "__main__":
    main()
