"""Analysis: IAM Deal Inventory Overview. Plan: plan.md. Writes output/. Generated by scaffold_report.py."""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))
from tools.load_data import load_sheet, load_source  # noqa: E402,F401

import pandas as pd  # noqa: E402,F401

OUT = HERE / "output"
OUT.mkdir(exist_ok=True)
logs = {}

# ---- load (logical sources always read the current file; do not change)
iam_deal_inventory, logs["iam_deal_inventory"] = load_source("iam_deal_inventory", "IAM Deal Inventory")

# ============================ analysis ============================
KPI_KEY = "notional_in_ccy"
MEASURE = "Notional in CCY"

# "Notional in CCY" is a stock (semi-additive over time). The file is already a single-date
# snapshot of outstanding deals (one Reporting Date), so the full file is the position in scope -
# it is never summed across dates.
in_scope = iam_deal_inventory
as_of = in_scope["Reporting Date"].max()
position = in_scope[in_scope["Reporting Date"] == as_of].copy()

total_notional = float(position[MEASURE].sum())

# ---- 1. Total notional by deal type (Loan vs Deposit)
by_deal_type = (
    position.groupby("Deal Type")[MEASURE]
    .agg(Notional="sum", Deals="count")
    .reset_index()
    .rename(columns={"Deal Type": "Deal Type"})
    .sort_values("Notional", ascending=False)
)
by_deal_type["Share of Total"] = by_deal_type["Notional"] / total_notional

# ---- 2. Total notional maturing within 7 / 30 / 90 / 365 days of the reporting date
windows = [7, 30, 90, 365]
maturity_window_rows = []
for w in windows:
    cutoff = as_of + pd.Timedelta(days=w)
    in_window = position[(position["Maturity Date"] > as_of) & (position["Maturity Date"] <= cutoff)]
    maturity_window_rows.append(
        {
            "Window": f"Next {w} days",
            "Notional": float(in_window[MEASURE].sum()),
            "Deals": int(len(in_window)),
            "Share of Total": float(in_window[MEASURE].sum()) / total_notional,
        }
    )
maturity_windows = pd.DataFrame(maturity_window_rows)

# ---- 3. Maturity profile by calendar year
by_year = position.copy()
by_year["Maturity Year"] = by_year["Maturity Date"].dt.year
maturity_by_year = (
    by_year.groupby("Maturity Year")[MEASURE]
    .agg(Notional="sum", Deals="count")
    .reset_index()
    .sort_values("Maturity Year")
)
maturity_by_year["Share of Total"] = maturity_by_year["Notional"] / total_notional

# ---- 4. Notional exposure by currency
by_currency = (
    position.groupby("CCY")[MEASURE]
    .agg(Notional="sum", Deals="count")
    .reset_index()
    .rename(columns={"CCY": "Currency"})
    .sort_values("Notional", ascending=False)
)
by_currency["Share of Total"] = by_currency["Notional"] / total_notional

# ---- 5. Loan / Deposit split by portfolio
portfolio_split = (
    position.groupby(["Murex Portfolio", "Deal Type"])[MEASURE]
    .sum()
    .unstack("Deal Type", fill_value=0.0)
    .reset_index()
)
for col in ("Loan", "Deposit"):
    if col not in portfolio_split.columns:
        portfolio_split[col] = 0.0
portfolio_split["Total"] = portfolio_split["Loan"] + portfolio_split["Deposit"]
portfolio_split = portfolio_split.sort_values("Total", ascending=False)[
    ["Murex Portfolio", "Loan", "Deposit", "Total"]
]

kpis = {
    KPI_KEY: total_notional,
    "as_of": as_of.strftime("%Y-%m-%d"),
    "rows_in_scope": int(len(position)),
    "currency": "EUR",
    "total_loan": float(by_deal_type.loc[by_deal_type["Deal Type"] == "Loan", "Notional"].sum()),
    "total_deposit": float(by_deal_type.loc[by_deal_type["Deal Type"] == "Deposit", "Notional"].sum()),
    "maturing_next_7d": float(maturity_windows.loc[maturity_windows["Window"] == "Next 7 days", "Notional"].iloc[0]),
    "maturing_next_30d": float(maturity_windows.loc[maturity_windows["Window"] == "Next 30 days", "Notional"].iloc[0]),
    "maturing_next_90d": float(maturity_windows.loc[maturity_windows["Window"] == "Next 90 days", "Notional"].iloc[0]),
    "maturing_next_365d": float(maturity_windows.loc[maturity_windows["Window"] == "Next 365 days", "Notional"].iloc[0]),
}
tables = {
    "by_deal_type": by_deal_type,
    "maturity_windows": maturity_windows,
    "maturity_by_year": maturity_by_year,
    "by_currency": by_currency,
    "portfolio_split": portfolio_split,
}
# ========================================================================

for name, df in tables.items():
    df.to_csv(OUT / f"{name}.csv", index=False)
(OUT / "kpis.json").write_text(json.dumps(kpis, indent=2, default=str))
(OUT / "data_log.json").write_text(json.dumps(logs, indent=2))
print(json.dumps(kpis, indent=2, default=str))
for name, df in tables.items():
    print(f"\n{name}\n{df.head(15).to_string()}")
