"""Checks for deal_inventory_overview. Generated by scaffold_report.py.
Recomputes the headline independently and runs the standard checks automatically."""
import json
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))
from tools.load_data import load_profile, load_sheet, load_source, load_source_profile  # noqa: E402,F401
from tools.validate import Validator  # noqa: E402

REPORT = "deal_inventory_overview"
MAIN = ("iam_deal_inventory", "IAM Deal Inventory")
load_main = load_source
main_profile = load_source_profile
SOURCE_MEASURE = "Notional in CCY"          # column in the source
ADDITIVITY = "semi_additive over time"
DATE_COL = "Reporting Date"                 # the file is a single-date snapshot; this is the as-of column
CURRENCY_COL = "CCY"
CONVERTED = False                       # every row is EUR; no conversion needed (checked below)
KPI_KEY = "notional_in_ccy"                 # key in output/kpis.json
OUTPUT_MEASURE = "__no_direct_match__"      # tables use "Notional"/"Loan"+"Deposit"; checked explicitly below
GRAIN_KEYS = ["Murex Original ID", "Murex ID"]             # columns that should be unique together
KEY_COLUMNS = ["Reporting Date", "Deal Type", "CCY", "Maturity Date", "Notional in CCY", "Murex Portfolio", "Rate in %"]           # dimensions/measures that must not be null

v = Validator(REPORT, review_level="full")
out = HERE / "output"
kpis = json.loads((out / "kpis.json").read_text())

# ---- independent recompute (applies the same "single snapshot, no filters" scope as the plan)
src, _ = load_main(*MAIN)
in_scope = src

# ---- standard checks (no changes needed)
if ADDITIVITY.startswith("semi_additive") and DATE_COL:
    as_of = pd.Timestamp(kpis["as_of"])
    basis = in_scope[in_scope[DATE_COL] == as_of]
    v.check("Stock measure taken at a single as-of date", "as_of" in kpis, f"as_of={as_of.date()}")
    v.reconcile(f"Headline {KPI_KEY} at {as_of.date()} vs independent recompute",
                float(basis[SOURCE_MEASURE].sum()), kpis[KPI_KEY])
    v.row_count("Rows at the as-of date", len(basis), kpis["rows_in_scope"])
else:
    basis = in_scope
    v.reconcile(f"Headline {KPI_KEY} vs independent recompute", float(basis[SOURCE_MEASURE].sum()), kpis[KPI_KEY])
    v.row_count("Rows in scope", len(basis), kpis["rows_in_scope"])
if CURRENCY_COL:
    n_ccy = basis[CURRENCY_COL].nunique()
    v.check("Headline in a single currency, or converted", n_ccy <= 1 or CONVERTED,
            f"{n_ccy} currencies: {sorted(basis[CURRENCY_COL].dropna().astype(str).unique())[:8]}")
for csv in sorted(out.glob("*.csv")):
    t = pd.read_csv(csv)
    if OUTPUT_MEASURE in t.columns:
        if ADDITIVITY.startswith("semi_additive") and DATE_COL and t.columns[0] == DATE_COL:
            v.reconcile(f"{csv.stem}: last date equals headline", kpis[KPI_KEY], float(t[OUTPUT_MEASURE].iloc[-1]))
        else:
            v.reconcile(f"{csv.stem} sums to headline", kpis[KPI_KEY], float(t[OUTPUT_MEASURE].sum()))
    if csv.stem != "maturity_windows":  # cumulative overlapping windows by design, not a partition
        for share in [c for c in t.columns if c.lower() == "share of total"]:
            v.shares_sum_to_one(t[share])
if GRAIN_KEYS:
    v.unique(in_scope, GRAIN_KEYS, label=f"Grain: {GRAIN_KEYS} unique")
v.no_nulls(basis, [c for c in KEY_COLUMNS if c in basis.columns])
for q in main_profile(MAIN[0])["annotations"].get("open_questions", []):
    v.warn("Open question carried into report", q)

# ---- extra checks specific to this report's tables ----

# 1. by_deal_type.csv: Loan + Deposit notional must equal the headline total (full partition)
by_deal_type = pd.read_csv(out / "by_deal_type.csv")
v.reconcile("by_deal_type: Notional sums to headline", kpis[KPI_KEY], float(by_deal_type["Notional"].sum()))
v.reconcile("by_deal_type: Loan matches independent recompute",
            float(basis.loc[basis["Deal Type"] == "Loan", SOURCE_MEASURE].sum()), kpis["total_loan"])
v.reconcile("by_deal_type: Deposit matches independent recompute",
            float(basis.loc[basis["Deal Type"] == "Deposit", SOURCE_MEASURE].sum()), kpis["total_deposit"])

# 2. maturity_windows.csv: each window recomputed independently (windows overlap by design, so they
#    do not sum to the headline - each is checked against its own independent recompute instead)
maturity_windows = pd.read_csv(out / "maturity_windows.csv")
for days, kpi_key in [(7, "maturing_next_7d"), (30, "maturing_next_30d"),
                      (90, "maturing_next_90d"), (365, "maturing_next_365d")]:
    cutoff = as_of + pd.Timedelta(days=days)
    expected = float(basis[(basis["Maturity Date"] > as_of) & (basis["Maturity Date"] <= cutoff)][SOURCE_MEASURE].sum())
    v.reconcile(f"maturity_windows: next {days} days matches independent recompute", expected, kpis[kpi_key])
v.check("Maturity windows are monotonically increasing (7d <= 30d <= 90d <= 365d)",
        kpis["maturing_next_7d"] <= kpis["maturing_next_30d"] <= kpis["maturing_next_90d"] <= kpis["maturing_next_365d"],
        f"{kpis['maturing_next_7d']:,.0f} / {kpis['maturing_next_30d']:,.0f} / "
        f"{kpis['maturing_next_90d']:,.0f} / {kpis['maturing_next_365d']:,.0f}")

# 3. maturity_by_year.csv: full partition of the position by calendar year -> sums to headline
maturity_by_year = pd.read_csv(out / "maturity_by_year.csv")
v.reconcile("maturity_by_year: Notional sums to headline", kpis[KPI_KEY], float(maturity_by_year["Notional"].sum()))

# 4. by_currency.csv: single-currency file -> exactly one row, equal to the headline
by_currency = pd.read_csv(out / "by_currency.csv")
v.check("by_currency: exactly one currency row (EUR-only book)", len(by_currency) == 1, f"{len(by_currency)} row(s)")
v.reconcile("by_currency: Notional sums to headline", kpis[KPI_KEY], float(by_currency["Notional"].sum()))

# 5. portfolio_split.csv: Loan + Deposit columns must equal Total, and Total sums to the headline
portfolio_split = pd.read_csv(out / "portfolio_split.csv")
v.check("portfolio_split: Loan + Deposit equals Total per portfolio",
        bool((portfolio_split["Loan"] + portfolio_split["Deposit"] - portfolio_split["Total"]).abs().max() < 0.01))
v.reconcile("portfolio_split: Total sums to headline", kpis[KPI_KEY], float(portfolio_split["Total"].sum()))

v.save()
